import{Decoder,Stream}from"https://cdn.jsdelivr.net/npm/@garmin/fitsdk@21.208.0/src/index.js";

const SCOPE="https://www.googleapis.com/auth/drive.file",ROOT="Iron Man Training Data",APP="garmin-workout-reviewer";
const $=s=>document.querySelector(s),el={client:$("#client-id"),connect:$("#connect-drive"),driveStatus:$("#drive-status"),file:$("#fit-file"),fileName:$("#file-name"),notes:$("#athlete-notes"),parse:$("#parse-fit"),parseStatus:$("#parse-status"),results:$("#results-panel"),integrity:$("#integrity-status"),grid:$("#summary-grid"),groups:$("#message-groups"),dlAnalysis:$("#download-analysis"),dlFull:$("#download-full"),save:$("#save-panel"),upload:$("#upload-drive"),uploadStatus:$("#upload-status"),driveResult:$("#drive-result"),log:$("#log"),clear:$("#clear-log")};
const state={file:null,token:null,tokenClient:null,full:null,analysis:null};

el.file.onchange=()=>{state.file=el.file.files?.[0]||null;el.fileName.textContent=state.file?`${state.file.name} · ${bytes(state.file.size)}`:"No file selected";el.parse.disabled=!state.file;status(el.parseStatus,state.file?"Ready to parse":"Waiting for file",state.file?"good":"neutral")};
el.connect.onclick=connectDrive;el.parse.onclick=parseFit;el.dlAnalysis.onclick=()=>download(state.analysis,analysisName());el.dlFull.onclick=()=>download(state.full,fullName());el.upload.onclick=uploadPackage;el.clear.onclick=()=>el.log.textContent="";

async function connectDrive(){const id=el.client.value.trim();if(!id.endsWith(".apps.googleusercontent.com")){status(el.driveStatus,"Enter a valid client ID","bad");return note("OAuth client ID is missing or malformed.")}try{status(el.driveStatus,"Opening Google","working");await waitGoogle();state.tokenClient=google.accounts.oauth2.initTokenClient({client_id:id,scope:SCOPE,callback:r=>{if(r.error){status(el.driveStatus,"Connection failed","bad");return note(r.error_description||r.error)}state.token=r.access_token;status(el.driveStatus,"Drive connected","good");note("Google Drive connected with drive.file access.")},error_callback:e=>{status(el.driveStatus,"Connection cancelled","warn");note(`Authorization did not complete: ${e.type||"unknown"}`)}});state.tokenClient.requestAccessToken({prompt:"consent"})}catch(e){status(el.driveStatus,"Connection failed","bad");fail(e)}}
async function waitGoogle(){const start=Date.now();while(!window.google?.accounts?.oauth2){if(Date.now()-start>10000)throw Error("Google Identity Services did not load.");await new Promise(r=>setTimeout(r,100))}}

async function parseFit(){if(!state.file)return;el.parse.disabled=true;el.results.classList.add("hidden");el.save.classList.add("hidden");status(el.parseStatus,"Decoding FIT","working");note(`Reading ${state.file.name}...`);try{const stream=Stream.fromArrayBuffer(await state.file.arrayBuffer()),decoder=new Decoder(stream);if(!decoder.isFIT())throw Error("The selected file does not contain a valid FIT header.");let integrity=false;try{integrity=decoder.checkIntegrity()}catch(e){note(`Integrity check warning: ${msg(e)}`)}const out=decoder.read({applyScaleAndOffset:true,expandSubFields:true,expandComponents:true,convertTypesToStrings:true,convertDateTimesToDates:true,includeUnknownData:true,mergeHeartRates:true,decodeMemoGlobs:true,legacyArrayMode:false});const messages=safe(out.messages),errors=safe(out.errors||[]),summary=summarize(messages,state.file,integrity,errors),notes=el.notes.value.trim();state.full={schemaVersion:1,generatedAt:new Date().toISOString(),source:fileMeta(state.file),fitIntegrityPassed:integrity,decodeErrors:errors,athleteNotes:notes,messages};state.analysis={schemaVersion:1,generatedAt:new Date().toISOString(),purpose:"Analysis-ready Garmin FIT extraction for the Iron Man Haines City ChatGPT project",source:{fileName:state.file.name,sizeBytes:state.file.size,fitIntegrityPassed:integrity,decodeErrors:errors},athleteNotes:notes,summary,sessions:group(messages,"session"),laps:group(messages,"lap"),records:group(messages,"record"),events:group(messages,"event"),lengths:group(messages,"length"),activities:group(messages,"activity"),workoutSteps:group(messages,"workoutStep"),workouts:group(messages,"workout"),deviceInfos:group(messages,"deviceInfo"),fileIds:group(messages,"fileId"),fieldDescriptions:group(messages,"fieldDescription"),developerDataIds:group(messages,"developerDataId"),hrv:group(messages,"hrv"),recordFields:summary.recordFields,availableMessageGroups:summary.messageGroupCounts};render(summary);el.results.classList.remove("hidden");el.save.classList.remove("hidden");status(el.parseStatus,"Decoded","good");status(el.integrity,integrity?"Integrity passed":"Integrity warning",integrity?"good":"warn");note(`Decoded ${summary.recordCount.toLocaleString()} records across ${Object.keys(summary.messageGroupCounts).length} message groups.`)}catch(e){status(el.parseStatus,"Parse failed","bad");fail(e)}finally{el.parse.disabled=!state.file}}

function summarize(m,f,integrity,errors){const sessions=group(m,"session"),laps=group(m,"lap"),records=group(m,"record"),events=group(m,"event"),lengths=group(m,"length"),s=sessions[0]||{},counts=Object.fromEntries(Object.entries(m).map(([k,v])=>[k,Array.isArray(v)?v.length:v==null?0:1]).sort(([a],[b])=>a.localeCompare(b))),fields=[...new Set(records.flatMap(r=>Object.keys(r||{})))].sort();return{sourceFile:f.name,sourceSizeBytes:f.size,fitIntegrityPassed:integrity,decodeErrorCount:errors.length,sport:first(s,["sport"])||first(group(m,"sport")[0]||{},["sport"])||"unknown",subSport:first(s,["subSport","sub_sport"]),startTime:date(first(s,["startTime","start_time","timestamp"])),totalElapsedTimeSeconds:num(first(s,["totalElapsedTime","total_elapsed_time"])),totalTimerTimeSeconds:num(first(s,["totalTimerTime","total_timer_time"])),totalDistanceMeters:num(first(s,["totalDistance","total_distance"])),avgHeartRate:num(first(s,["avgHeartRate","avg_heart_rate"]))??stats(records,["heartRate","heart_rate"]).avg,maxHeartRate:num(first(s,["maxHeartRate","max_heart_rate"]))??stats(records,["heartRate","heart_rate"]).max,avgPower:num(first(s,["avgPower","avg_power"]))??stats(records,["power"]).avg,maxPower:num(first(s,["maxPower","max_power"]))??stats(records,["power"]).max,normalizedPower:num(first(s,["normalizedPower","normalized_power"])),avgCadence:num(first(s,["avgCadence","avg_cadence"]))??stats(records,["cadence"]).avg,recordCount:records.length,lapCount:laps.length,eventCount:events.length,lengthCount:lengths.length,recordFields:fields,messageGroupCounts:counts}}
function group(m,name){const n=norm(name),hit=Object.entries(m).find(([k])=>norm(k).replace(/mesgs$|messages$|message$/g,"")===n);return hit?(Array.isArray(hit[1])?hit[1]:[hit[1]]):[]}
const norm=v=>String(v).replace(/[^a-z0-9]/gi,"").toLowerCase();function first(o,keys){for(const k of keys)if(o?.[k]!==undefined&&o[k]!==null)return o[k];return null}function num(v){if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v==="string"&&v.trim()!==""&&Number.isFinite(Number(v)))return Number(v);return null}function stats(records,keys){const a=records.map(r=>num(first(r,keys))).filter(v=>v!==null);return a.length?{avg:Math.round(a.reduce((x,y)=>x+y,0)/a.length*10)/10,max:Math.max(...a)}:{avg:null,max:null}}function date(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function safe(v,seen=new WeakSet()){if(v==null)return v??null;if(typeof v==="bigint")return String(v);if(typeof v==="number")return Number.isFinite(v)?v:null;if(typeof v!=="object")return v;if(v instanceof Date)return v.toISOString();if(v instanceof ArrayBuffer)return [...new Uint8Array(v)];if(ArrayBuffer.isView(v))return [...v];if(seen.has(v))return"[Circular]";seen.add(v);if(Array.isArray(v))return v.map(x=>safe(x,seen));return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,safe(x,seen)]))}

function render(s){const metrics=[["Sport",[s.sport,s.subSport].filter(Boolean).join(" / ")],["Started",s.startTime?new Date(s.startTime).toLocaleString():"Unknown"],["Distance",distance(s.totalDistanceMeters)],["Timer time",duration(s.totalTimerTimeSeconds??s.totalElapsedTimeSeconds)],["Records",s.recordCount.toLocaleString()],["Laps",s.lapCount.toLocaleString()],["Avg / max HR",pair(s.avgHeartRate,s.maxHeartRate," bpm")],["Avg / NP",pair(s.avgPower,s.normalizedPower," W")]];el.grid.innerHTML=metrics.map(([a,b])=>`<div class="metric"><span class="metric-label">${html(a)}</span><span class="metric-value">${html(b||"—")}</span></div>`).join("");el.groups.textContent=Object.entries(s.messageGroupCounts).map(([k,v])=>`${k}: ${v}`).join("\n")}

async function uploadPackage(){if(!state.analysis||!state.full||!state.file)return note("Parse a FIT file first.");if(!state.token){status(el.uploadStatus,"Connect Drive first","warn");return note("Google Drive is not connected.")}el.upload.disabled=true;status(el.uploadStatus,"Uploading","working");el.driveResult.textContent="";try{const root=await findRoot(),folder=await createFolder(folderName(),root.id,{app:APP,artifactType:"activity-folder"});await uploadFile(state.file.name,state.file,"application/octet-stream",folder.id,"original-fit");await uploadFile(analysisName(),jsonBlob(state.analysis),"application/json",folder.id,"analysis-json");await uploadFile(fullName(),jsonBlob(state.full),"application/json",folder.id,"decoded-full-json");await uploadFile("athlete-notes.md",notesBlob(),"text/markdown",folder.id,"athlete-notes");const url=`https://drive.google.com/drive/folders/${folder.id}`;el.driveResult.innerHTML=`Saved successfully: <a href="${url}" target="_blank" rel="noopener">open activity folder</a>`;status(el.uploadStatus,"Saved to Drive","good");note(`Upload complete: ${url}`)}catch(e){if(msg(e).includes("401")){state.token=null;status(el.driveStatus,"Reconnect required","warn")}status(el.uploadStatus,"Upload failed","bad");fail(e)}finally{el.upload.disabled=false}}
async function findRoot(){const q=[`name='${driveEscape(ROOT)}'`,`mimeType='application/vnd.google-apps.folder'`,`trashed=false`,`appProperties has { key='app' and value='${APP}' }`].join(" and "),r=await drive(`https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=10&fields=files(id,name,webViewLink)&q=${encodeURIComponent(q)}`);if(r.files?.[0])return r.files[0];note(`Creating Drive folder: ${ROOT}`);return createFolder(ROOT,null,{app:APP,artifactType:"root-folder"})}
async function createFolder(name,parent,props){return drive("https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",...(parent?{parents:[parent]}:{}),appProperties:props})})}
async function uploadFile(name,blob,type,parent,artifactType){note(`Uploading ${name} (${bytes(blob.size)})...`);const meta=await drive("https://www.googleapis.com/drive/v3/files?fields=id,name",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,parents:[parent],mimeType:type,appProperties:{app:APP,artifactType}})});await drive(`https://www.googleapis.com/upload/drive/v3/files/${meta.id}?uploadType=media&fields=id,name,size`,{method:"PATCH",headers:{"Content-Type":type},body:blob});return meta}
async function drive(url,opt={}){const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${state.token}`,...(opt.headers||{})}});if(!r.ok)throw Error(`Google Drive API ${r.status}: ${(await r.text()).slice(0,1200)}`);const t=await r.text();return t?JSON.parse(t):{}}

function folderName(){const s=state.analysis.summary,d=s.startTime?new Date(s.startTime):new Date(state.file.lastModified||Date.now()),stamp=(Number.isNaN(d.getTime())?new Date():d).toISOString().slice(0,16).replace("T","_").replace(":","-");return`${stamp}_${slug(s.sport||"activity")}_${slug(state.file.name.replace(/\.fit$/i,""))}`.slice(0,170)}
const analysisName=()=>`${state.file?.name.replace(/\.fit$/i,"")||"activity"}.analysis.json`,fullName=()=>`${state.file?.name.replace(/\.fit$/i,"")||"activity"}.decoded-full.json`;
function notesBlob(){const s=state.analysis.summary,n=state.analysis.athleteNotes||"No subjective notes were entered.";return new Blob([[`# ${state.file.name}`,"",`- Sport: ${s.sport}${s.subSport?` / ${s.subSport}`:""}`,`- Start: ${s.startTime||"unknown"}`,`- Source FIT integrity: ${s.fitIntegrityPassed?"passed":"warning"}`,"","## Athlete notes","",n,"","## Suggested ChatGPT prompt","","Review this activity using my Iron Man Haines City project context. Start with the athlete notes, then evaluate execution, physiology, technique, and the next training decision.",""].join("\n")],{type:"text/markdown"})}
const jsonBlob=v=>new Blob([JSON.stringify(v,null,2)],{type:"application/json"});function download(v,name){if(!v)return;const u=URL.createObjectURL(jsonBlob(v)),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const fileMeta=f=>({fileName:f.name,sizeBytes:f.size,lastModified:f.lastModified?new Date(f.lastModified).toISOString():null,mediaType:f.type||"application/octet-stream"});function status(node,text,kind){node.textContent=text;node.className=`status ${kind}`}function note(t){const stamp=new Date().toLocaleTimeString();el.log.textContent=`${el.log.textContent?el.log.textContent+"\n":""}[${stamp}] ${t}`;el.log.scrollTop=el.log.scrollHeight}function fail(e){console.error(e);note(`ERROR: ${msg(e)}`)}const msg=e=>e instanceof Error?e.message:String(e);function bytes(n){if(!Number.isFinite(n))return"—";if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}function distance(m){return m==null?"—":m>=1000?`${(m/1000).toFixed(2)} km`:`${Math.round(m)} m`}function duration(s){if(s==null)return"—";const n=Math.max(0,Math.round(s)),h=Math.floor(n/3600),m=Math.floor(n%3600/60),x=n%60;return[h,m,x].map((v,i)=>i?String(v).padStart(2,"0"):String(v)).join(":")}const pair=(a,b,s)=>a==null&&b==null?"—":`${a??"—"} / ${b??"—"}${s}`;const slug=v=>String(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase()||"activity";const driveEscape=v=>String(v).replace(/\\/g,"\\\\").replace(/'/g,"\\'");const html=v=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
